"""ORM Model

Revision ID: a008b1f94ac4
Revises: ae4719c794e1
Create Date: 2023-06-03 23:16:59.434236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a008b1f94ac4'
down_revision = 'ae4719c794e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'restaurant_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('desc', sa.Text(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.Column('update_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=30), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('is_oauth', sa.Boolean(), nullable=True),
        sa.Column('is_enable', sa.Boolean(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.Column('update_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table(
        'oauth',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('provider', sa.String(length=30), nullable=False),
        sa.Column('access_token', sa.String(length=128), nullable=False),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.Column('update_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'restaurant_type_intermediay',
        sa.Column('restaurant_id', sa.Integer(), nullable=False),
        sa.Column('restaurant_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['restaurant_id'],
            ['restaurant.id'],
        ),
        sa.ForeignKeyConstraint(
            ['restaurant_type_id'],
            ['restaurant_type.id'],
        ),
        sa.PrimaryKeyConstraint('restaurant_id', 'restaurant_type_id'),
    )
    op.create_table(
        'user_restaurant_intermediary',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['restaurant_id'],
            ['restaurant.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('user_id', 'restaurant_id'),
    )
    op.add_column('restaurant', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('restaurant', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_column('restaurant', 'price')
    op.drop_column('restaurant', 'desc')
    op.drop_table('user_restaurant_intermediary')
    op.drop_table('restaurant_type_intermediay')
    op.drop_table('oauth')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('restaurant_type')
    # ### end Alembic commands ###
