"""create restaurant_open_time table

Revision ID: ae4719c794e1
Revises: Create restaurant_open_time table
Create Date: 2023-05-10 15:45:06.237473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4719c794e1'
down_revision = 'bf9ebef8b5a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'restaurant_open_time',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=False),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('open_time', sa.Time(), nullable=False),
        sa.Column('close_time', sa.Time(), nullable=False),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.Column('update_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['restaurant_id'],
            ['restaurant.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_restaurant_id', 'restaurant_open_time', ['restaurant_id'], unique=False)
    op.create_index(
        'idx_restaurant_id_day_of_week',
        'restaurant_open_time',
        ['restaurant_id', 'day_of_week'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restaurant_id_day_of_week', table_name='restaurant_open_time')
    op.drop_index('idx_restaurant_id', table_name='restaurant_open_time')
    op.drop_table('restaurant_open_time')
    # ### end Alembic commands ###
