"""create restaurant table

Revision ID: bf9ebef8b5a1
Revises: Create restaurant table
Create Date: 2023-05-10 15:31:03.378219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9ebef8b5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'restaurant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('address', sa.Text(), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lng', sa.Float(), nullable=False),
        sa.Column('is_enable', sa.Boolean(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.Column('update_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_lat_lng', 'restaurant', ['lat', 'lng'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lat_lng', table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
